language: node_js

node_js:
  - "10"
  
cache: yarn

stages:
  - test
  - version
  - build
  - deploy

jobs:
  include:
    - stage: test
      name: test
      services:
        - mysql
      before_script:
        - mysql -e 'create database todo;'
        - mysql -u root -e "create user todo identified by 'password'; grant all on todo.* to todo;"
        
      script:
        - yarn install 
        - yarn workspace db migrate:up 
        - yarn test:core
        - yarn test:ui 
      branches:
        except:
          - tags
    
    - stage: version
      name: revision
      if: branch = master
      script: 
        - yarn install
        - yarn release

